---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: fluent-bit
  namespace: gitops-system
spec:
  serviceAccountName: platform-gitops-sa
  packageRef:
    refName: fluent-bit.tanzu.vmware.com
    versionSelection:
      constraints: 2.1.2+vmware.1-tkg.1
  values:
  - secretRef:
      name: fluent-bit-packages-values