apiVersion: v1
kind: Namespace
metadata:
  name: tmc-gitops

---   
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-gitops-sa
  namespace: tmc-gitops

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-cluster-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-admin-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: platform-gitops-sa
  namespace: tmc-gitops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin-cluster-role

---

