apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../base/

secretGenerator:
- name: fluent-bit-packages-values
  namespace: tmc-gitops
  files:
  - values.yml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: fluent-bit-packages
