certificates:
  duration: 8760h
  renewBefore: 360h
contour:
  listenIPFamily: IPv4
  logLevel: info
  pspNames: vmware-system-restricted
  replicas: 2
  useProxyProtocol: false
envoy:
  hostNetwork: false
  hostPorts:
    enable: true
    http: 80
    https: 443
  listenIPFamily: IPv4
  logLevel: info
  pspNames: ""
  service:
    disableWait: false
    loadBalancerTLSTermination: false
    nodePorts:
      http: 0
      https: 0
    type: LoadBalancer
  terminationGracePeriodSeconds: 300
  workload:
    replicas: 2
    type: DaemonSet
infrastructure_provider: vsphere
namespace: tanzu-system-ingress
